version: '3.8'

networks:
  default:

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    ports:
      - ${MYSQL_PORT}:$MYSQL_PORT
    volumes:
      - "mysql_data:/var/lib/mysql"
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - ${APP_PORT}:$APP_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false",
            "spring.datasource.username" : "${MYSQL_USER}",
            "spring.datasource.password" : "${MYSQL_PASSWORD}",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "api.auth.token" : "${URLSHORTENER_API_TOKEN}"
          }'
    stdin_open: true
    tty: true

volumes:
  mysql_data: