version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:5.7
    container_name: links-db
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_APP_URLSHORTENER_USER: app-urlshortener
      MYSQL_APP_URLSHORTENER_PASSWORD: password
      MYSQL_DATABASE: urlshortener